### ISSUE TITLE
Support PAP login

### ISSUE THREAD

**Issue by mpangrazzi** [mpangrazzi/pepper#1]
It would be nice to add PAP logon support, since it seems like CoovaChilli JSON interface [already supports it](https://github.com/coova/coova-chilli/blob/master/src/redir.c#L2331). 

Basically, during logon, instead of passing a CHAP challenge in `response` field, we have to pass a `password` field containig the password in plain-text.

**Comment by Spomky** [comment]
:+1:

**Comment by mpangrazzi** [comment]
I've added PAP authentication protocol support in `pap`. In a few days I'll test it on a real production deployment, and if it's ok, I'll merge it and release version 1.2.0.
