### ISSUE TITLE
{ [Error: socket hang up] code: 'ECONNRESET' }

### ISSUE THREAD

**Issue by imtase** [mpangrazzi/pepper#4]
Try to use chilli-pepper but have this message : { [Error: socket hang up] code: 'ECONNRESET' }

All on the same server (2 ethernet cards)

Nodejs 4.2.2
Coovachilli 1.3.0
Freeradius 3

**Comment by mpangrazzi** [comment]
Hi,

I'll be glad to help, but I need more informations:
- Are you using it from client (browser) or from node.js (server)? 
- Could you describe better your environment?
- Have you tried to run pepper with [debug](https://github.com/mpangrazzi/pepper#debug)?

**Comment by imtase** [comment]
I have try in 2 ways:

1st: one page with just chilli-pepper for testing (lunch by nodeJS command on the server)
2nd: from an api call by browser in MEAN application (I use generator-angular-fullstack)

For the 2 ways the application is on a same server than coovachilli, it could be a problem?

The environment is like this:

Ubuntu 14.04 with 2 eth (tun with coovachilli) with: Freeradius 3 / Coovachilli 1.3.0 & 1 MEAN application for management of a wifi network.

Freeradius/Coovachilli working well

**Comment by mpangrazzi** [comment]
Ok. So you're seeing the **socket hang up** error both in node and the browser. This could happen if you make chilli-pepper point to the wrong `host` / `port`. 

Are you sure that `host` and `port` options are actually CoovaChilli's host and port?

You could check that easily: 
1. Join the Wi-Fi (or wired) network. You'll get an IP address from CoovaChilli's DHCP.
2. Check your gateway IP address (usually from your OS network preferences). It **should** be CoovaChilli's IP address, and it **should** equal to `host` option of chilli-pepper. Default `port` is usually 3990. Also, you can check if CoovaChilli is correctly online by doing `curl http://{your-gateway-ip}:3990/json/status`. You should see a JSON response from CoovaChilli.
3. Log on using chiilli-pepper, calling `logon` method from your browser or node.
