### ISSUE TITLE
Error when importing is EcmaScript 6 project

### ISSUE THREAD

**Issue by heruan** [mpangrazzi/pepper#5]
When using `chilli-pepper` in an EcmaScript 6 project (e.g. Aurelia), like this:

``` javascript
import {Pepper} from 'chilli-pepper';

export class Chilli {
    constructor() {
        this.pepper = Pepper({ host: '10.0.0.1', port: 3990 });
    }
}
```

I get multiple errors starting at (see also image):

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    inherits    @   inherits_browser.js:6
```

![screen shot 2016-01-19 at 11 10 46](https://cloud.githubusercontent.com/assets/851745/12415697/65006e5c-be9d-11e5-9080-828c72668cf3.png)

**Comment by mpangrazzi** [comment]
Hmm... This is weird.

I don't know Aurelia, but it seems to be using [Babel](https://babeljs.io) to transpile ES6 code. If you put your code in a file and then run something like:

``` bash
babel --presets es2015 yourfile.js
```

You will see a correct ES5 output, which means that ES6 to ES5 has been done _correctly_. 
But, I don't know how actually Aurelia is using Babel internally. Also, are you sure that your code is correct (i.e. for Aurelia framework code/structure conventions)?

However, I will add a ES6 working as soon as I can :)
