### ISSUE TITLE
Enable ssl on uamport 

### ISSUE THREAD

**Issue by tomasell** [mpangrazzi/pepper#6]
Using parameter `ssl:true`, client send request to https://{host}/json but chilli is not listen on uamport 443. I only found `--uamuissl`and permit uamuiport listen over ssl, but not uamport.
How can use your JS library over ssl?
Thanks!

**Comment by mpangrazzi** [comment]
Hi,

your question is regarding only Coova Chilli and not pepper itself. Anyway, I'll give you some hints :)

To make Coova Chilli listen to HTTPS requests, you have to edit Coova Chilli config file, usually placed in `/etc/chilli/config` and make sure that the following options are true:

``` bash
HS_TCP_PORTS="80 443"
HS_REDIRSSL=on
HS_SSLKEYFILE=/path/to/your-ssl-key.pem
HS_SSLCERTFILE=/path/to/your-ssl-certificate.pem
HS_UAMUISSL=on
```

Remember that you need an SSL certificate, or it will not work.

**Comment by heruan** [comment]
It seems that Pepper forces HTTPS connections to port 443, why? Listening to a different port over SSL should be totally valid. BTW, it's unclear how to make Coova Chilli listen on different HTTPS ports, but that's another story…

**Comment by mpangrazzi** [comment]
@heruan This is a bit out of topic :) 

Actually, I've never had (and want) to make Coova Chilli listen to a different SSL port, but it's trivial to implement on pepper side, and maybe it could be done in a further release. On Coova Chilli side, you should ask [them](https://github.com/coova/coova-chilli/issues).
