### ISSUE TITLE
chap: ERROR: Password comparison failed: password is incorrect

### ISSUE THREAD

**Issue by DarioAntuzzi** [mpangrazzi/pepper#8]
Hi,
I have a configuration with coovachilli 1.3.1.4 + freeradius 3.0.11 on UbuntuServer16.04
everything is ok with chilli default captive portal.
Now with a custom captive portal I wanted to use pepper to authenticate the user, but after calling the function `submit()` with the correct username(user) and password(pass) freeradius reply with:
_chap: ERROR: Password comparison failed: password is incorrect_
(see LogHotSpot.txt).
it seems there is an additional password conversion somewere between chilli and Freeradius.

`var pepper = new Pepper ({host: params.uamip, port: params.uamport});
`
`submit(){pepper.logon(username, password, {'protocol':'chap'}, (err, data) {});}
`
[LogHotSpot.txt](https://github.com/mpangrazzi/pepper/files/388089/LogHotSpot.txt)
[ChilliConfig.txt](https://github.com/mpangrazzi/pepper/files/388351/ChilliConfig.txt)

**First request:**

> curl 'http://10.1.0.1:3990/json/status?callback=__Pepper0' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36' -H 'Accept: _/_' -H 'Referer: http://99.99.99.99:99/login?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=e3f3e85d56bc3952765dd746549e97cb&called=08-00-27-79-7E-B7&mac=08-00-27-C1-04-44&ip=10.1.0.2&nasid=nas01&sessionid=5799d13e00000004&userurl=http%3a%2f%2fansa.it%2f&md=EB425EC630205300CD42C5A62CD4ABE4' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed

**Second request**

> curl 'http://10.1.0.1:3990/json/logon?username=user&response=7037fb680802a0f193b67d5ddc139d1b&callback=__Pepper1' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36' -H 'Accept: _/_' -H 'Referer: http://99.99.99.99:99/login?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=e3f3e85d56bc3952765dd746549e97cb&called=08-00-27-79-7E-B7&mac=08-00-27-C1-04-44&ip=10.1.0.2&nasid=nas01&sessionid=5799d13e00000004&userurl=http%3a%2f%2fansa.it%2f&md=EB425EC630205300CD42C5A62CD4ABE4' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed

Can you help me please thx

**Comment by mpangrazzi** [comment]
Hi,
- Have you disabled `uamsecret` option on CoovaChilli? If it's enabled, [JSON interface doesn't work correctly](https://github.com/coova/coova-chilli/issues/221). So, ensure that `uamsecret` option is disabled on CoovaChilli config.
- Have you checked the `err` variable? Also, your code is incorrect. In order to get the callback called, it should be like:

``` js
function submit () {
  pepper.logon(username, password, { protocol: 'chap' }, function (err, data) {
    console.log(err);
  });
} 
```
- Have you tried to enable [debug](https://github.com/visionmedia/debug#browser-support) on e.g. Chrome developer tools? To do that, open developer tools, go to the JS console and then `localStorage.debug = '*'`. After that, try to authenticate again and check console for error / debug messages.

**Comment by DarioAntuzzi** [comment]
Hi,
I tried your advice but nothing has changed.
I have disable `uamsecret` in chilli configuration.
err variable = null
`submit(){pepper.logon(username, password, {'protocol':'chap'}, (err, data) =>{ console.log("err", err); console.log("data", data); console.log("pepper", this.pepper); }); }`

**This is result of `localStorage.debug = '*`'**

> pepper starting logon for user - pass - protocol: chap +11s
> browser.js:112 jsonp jsonp req "http://10.1.0.1:3990/json/status?callback=__Pepper0" +5ms
> browser.js:112 jsonp jsonp got +19ms Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "116315294eae7611cb0ed8980bc2539e", location: Object…}
> browser.js:112 pepper computed CHAP-Password: d33f655aaf4ae4997e4a7e58c8e6e031 +6ms
> browser.js:112 pepper logon payload +3ms Object {username: "user", response: "d33f655aaf4ae4997e4a7e58c8e6e031"}
> browser.js:112 jsonp jsonp req "http://10.1.0.1:3990/json/logon?username=user&response=d33f655aaf4ae4997e4a7e58c8e6e031&callback=__Pepper1" +7ms
> browser.js:112 jsonp jsonp got +1s Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "55338ea0c239ca6efe1773126bfd00f3", redir: Object}
> login.ts:51 err null
> login.ts:52 data Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "55338ea0c239ca6efe1773126bfd00f3", redir: Object}
> login.ts:53 pepper Pepper {querystring: "?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=…%2fansa.it%2f&md=776CA00BEA7D7F5050F64F44B0B5ABFE", data: Object, status: Object, host: "10.1.0.1", port: 3990…}

For the `... function (err, data) ...`I have declared in a custom typescript 
[chilli-pepper.d.ts.txt](https://github.com/mpangrazzi/pepper/files/388403/chilli-pepper.d.ts.txt)

**Comment by DarioAntuzzi** [comment]
I tried to restart the machine and now the above code works only disable uamsecret.
Thanks a lot

**Comment by DarioAntuzzi** [comment]
I tried to PAP and the config does not work
`submit(){pepper.logon(username, password, {'protocol':'pap'}, (err, data) =>{ console.log("err", err); console.log("data", data); console.log("pepper", this.pepper); }); }`

in the log of freeradius:

```
(13)   User-Password = "\036\256"
...
(13) Found Auth-Type = PAP
(13) # Executing group from file /etc/freeradius/sites-enabled/default
(13)   Auth-Type PAP {
(13) pap: Login attempt with password
(13) pap: Comparing with "known good" Cleartext-Password
(13) pap: ERROR: Cleartext password "pass" does not match "known good" password
(13) pap: Passwords don't match
(13)     [pap] = reject
(13)   } # Auth-Type PAP = reject
(13) Failed to authenticate the user
(13) WARNING: Unprintable characters in the password.  Double-check the shared secret on the server and the NAS!
(13) Using Post-Auth-Type Reject
(13) # Executing group from file /etc/freeradius/sites-enabled/default
(13)   Post-Auth-Type REJECT {
```

> pepper starting logon for user - pass - protocol: pap +6s
> browser.js:112 jsonp jsonp req "http://10.1.0.1:3990/json/status?callback=__Pepper0" +4ms
> browser.js:112 jsonp jsonp got +18ms Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "1eae004d4d26b089f5caa952567fc1ac", location: Object…}
> browser.js:112 pepper logon payload +6ms Object {username: "user", password: "pass"}
> browser.js:112 jsonp jsonp req "http://10.1.0.1:3990/json/logon?username=user&password=pass&callback=__Pepper1" +6ms
> browser.js:112 jsonp jsonp got +1s Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "843bed65c06e235cc63b065fda6ed88c", redir: Object}
> login.ts:51 err null
> login.ts:52 data Object {version: "1.0", clientState: 0, nasid: "nas01", challenge: "843bed65c06e235cc63b065fda6ed88c", redir: Object}
> login.ts:53 pepper Pepper {querystring: "?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=…=579a059a00000003&userurl=http%3a%2f%2fansa.it%2f", data: Object, status: Object, host: "10.1.0.1", port: 3990…}

**Comment by mpangrazzi** [comment]
Hmm... `User-Password` is somewhat encoded on RADIUS side instead of being in cleartext (PAP), but Pepper is sending it in cleartext. Have you checked your CoovaChilli config and/or logs?

**Comment by DarioAntuzzi** [comment]
Chilli log seems sends password in clear-text
something in radius configuration?

```
coova-chilli[2898]: Address found
coova-chilli[3301]: The path: json/status
coova-chilli[3301]: The (json format) path: status
coova-chilli[3301]: The parameter callback is: [__Pepper0]
coova-chilli[2898]: caught 17 via selfpipe
coova-chilli[2898]: child 3301 terminated
coova-chilli[2898]: Freed child process 3301 [[redir]]
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[3302]: The path: json/logon
coova-chilli[3302]: The (json format) path: logon
coova-chilli[3302]: The parameter username is: [user]
coova-chilli[3302]: -->> Setting username=[user]
coova-chilli[3302]: using uamprotocol: WISPr 1.0 (1)
**coova-chilli[3302]: The parameter password is: [pass]**
coova-chilli[3302]: checking modules...
coova-chilli[3302]: redir_accept: Sending RADIUS request
coova-chilli[3302]: RADIUS client 0.0.0.0:0
coova-chilli[3302]: created radius packet (code=1, id=229, len=35)
coova-chilli[3302]: User password 2 [c�]
coova-chilli[3302]: sending radius packet (code=1, id=229, len=270)
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[3302]: Received RADIUS packet id=229
coova-chilli[3302]: RADIUS queue-out id=229 idx=0
coova-chilli[3302]: Received RADIUS response
coova-chilli[3302]: +attribute EAP msg (0 bytes):
coova-chilli[3302]: redir_main handling Access-Reject
coova-chilli[3302]: ---->>> resetting challenge: 60769f032ed4b55618efe83321a26a42
coova-chilli[3302]: The parameter callback is: [__Pepper1]
coova-chilli[3302]: -->> Msg userurl=[http://10.1.0.1:3990/favicon.ico]
coova-chilli[2898]: Address found
coova-chilli[2898]: Address found
coova-chilli[2898]: caught 17 via selfpipe
coova-chilli[2898]: child 3302 terminated
coova-chilli[2898]: Freed child process 3302 [[redir]]
coova-chilli[2898]: Address found
```

**Comment by mpangrazzi** [comment]
Not exactly, CoovaChilli is sending a challenge-encoded password (`coova-chilli[3302]: User password 2 [c�]`) instead of a cleartext one. Check your CoovaChilli configuration and ensure that it doesn't use a `challenge` (which is only for PAP method).

**Comment by DarioAntuzzi** [comment]
Where I can fid `challenge` configuration?
[ChilliConfig.txt](https://github.com/mpangrazzi/pepper/files/390092/ChilliConfig.txt)

**Comment by mpangrazzi** [comment]
If you run:

```
$ chilli --help
```

you will find a `--nochallenge` option. 

However, it's **not** the best practice and after looking at [those sources](https://github.com/coova/coova-chilli/blob/master/src/main-response.c#L115) it seems that CoovaChilli is actually using challenge _by default_ for PAP requests.

So: if you run chilli with `--nochallenge` option it should work. But I have to definitely reimplement PAP support in a more decent way. Or if you want, pull requests are welcome :)

**Comment by stevejohn82** [comment]
Hello , I donot get a login page with coova-chilli 1.3.0 =installed on openwrt 
 
"http://10.1.0.1:4990/www/login.chi?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=03601129976f03749a2369119695b00f&called=A4-2B-B0-B9-D1-42&mac=98-90-96-CF-58-4C&ip=10.1.0.3&nasid=nas01&sessionid=5890672900000002&userurl='.."

this is the url i get, and no login page appears saying 10.1.0.1 did not send anydata
![1](https://cloud.githubusercontent.com/assets/22586190/22495440/4bf22208-e862-11e6-91f5-eac36146d5f1.png)

**Comment by mpangrazzi** [comment]
Hi @stevejohn82, this seems to be a problem with your [coova-chilli](https://github.com/coova/coova-chilli) installation. You'd better ask [on their issue board](https://github.com/coova/coova-chilli/issues). Thanks!

**Comment by stevejohn82** [comment]
@mpangrazzi  I am done using html instead of chi, but i would love to use chi extensions for the modules they are offering(vouchers, accept only, signup etc) , Thanks a bunch

**Comment by mpangrazzi** [comment]
@stevejohn82 You're welcome. Keep in mind that you could easily use e.g. PHP or any other server-side technology in your custom portal. All `.chi` files are "powered" by [Haserl](http://haserl.sourceforge.net/) which is designed to run on low performance devices.

**Comment by stevejohn82** [comment]
@mpangrazzi  thank you for your reply, but i cannot use .chi files even with proper Haserl Installation, no worries i will use PHP and html instead
